language: objective-c
osx_image: xcode7.2
script:
  - xctool build -workspace DFDiff.xcworkspace -scheme DFDiff -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace DFDiff.xcworkspace -scheme DFDiffTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
